name: Publish GMod Workshop

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Build gmod-uploader image
              run: docker build -t gmod-uploader .

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install Python deps
              run: pip install steampy

            # Uncomment the following lines if you need to generate a Steam Guard OTP via shared_token
            # - name: Generate Steam Guard OTP
            # id: generate_otp
            # run: |
            # echo "otp=$(python3 otp.py)" >> $GITHUB_OUTPUT

            - name: Publish example-addon to Workshop
              env:
                  STEAM_USER: ${{ secrets.STEAM_USER }}
                  STEAM_PASS: ${{ secrets.STEAM_PASS }}
                  # STEAM_GUARD: ${{ steps.generate_otp.outputs.otp }}
                  PUBLISHED_FILE_ID: ${{ secrets.ADDON_ID }} # The ID of the workshop item to update, or 0 to create a new one
                  CONTENT_PATH: /data/example-addon
                  TITLE: 'example-addon v1.0.0'
                  DESCRIPTION: 'Continuous integration for Garry’s Mod'
                  VISIBILITY: '0' # 0=public (require steamguard),1=friends,2=private
              run: |
                  docker run --rm \
                    -e STEAM_USER \
                    -e STEAM_PASS \
                    -e STEAM_GUARD \
                    -e CONTENT_PATH \
                    -e TITLE \
                    -e DESCRIPTION \
                    -e VISIBILITY \
                    -e PUBLISHED_FILE_ID \
                    -v ${{ github.workspace }}/example-addon:/data/example-addon \
                    gmod-uploader
